import { mkdir, copyFile, cp } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const destination = new URL('client/webxr/vendor/', root);
await mkdir(destination, { recursive: true });
for (const name of ['three.core.js', 'three.module.js']) await copyFile(new URL(`node_modules/three/build/${name}`, root), new URL(name, destination));
await copyFile(new URL('node_modules/three/LICENSE', root), new URL('LICENSE', destination));
await cp(new URL('node_modules/three/examples/jsm/', root), new URL('addons/', destination), { recursive: true });
await mkdir(new URL('bvh/', destination), { recursive: true });
await copyFile(new URL('node_modules/three-mesh-bvh/build/index.module.js', root), new URL('bvh/index.js', destination));
await copyFile(new URL('node_modules/three-mesh-bvh/LICENSE', root), new URL('bvh/LICENSE', destination));
console.log('Pinned Three.js copied locally with its MIT license; no runtime CDN.');
